# created by @jcoreio/toolchain-circle

version: 2.1

# orbs:
#   codecov: codecov/codecov@4.1.0

jobs:
  build:
    machine:
      image: ubuntu-2404:current

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            nvm use
            npm config set --location user \
              "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" \
              "registry=https://registry.npmjs.org/"
            corepack enable
            pnpm i --frozen-lockfile
      - run:
          name: Prepublish
          command: |
            nvm use
            corepack enable
            [[ $(netstat -tnlp | grep -F 'circleci-agent') ]] || pnpm run tc prepublish
      # - codecov/upload
      - run:
          name: Release
          command: |
            nvm use
            corepack enable
            [[ $(netstat -tnlp | grep -F 'circleci-agent') ]] || pnpm run tc release

workflows:
  build:
    jobs:
      - build:
          context:
            - npm-release
            - github-release
            - aws-deployments
